@extends('layouts.portal')
@section('title','My Profile')
@section('content')
<div class="page-heading"><div><span class="eyebrow">MY ACCOUNT</span><h1>My profile</h1><p>Manage your personal information, location and account details.</p></div></div>
@if(session('status'))<div class="alert alert-success">{{ session('status') }}</div>@endif
@if($errors->any())<div class="alert alert-danger">{{ $errors->first() }}</div>@endif
<div class="profile-layout">
<section class="panel-card profile-card"><div class="profile-cover"></div><div class="profile-main"><span class="avatar xl">{{ collect(explode(' ',$user->name))->map(fn($part)=>$part[0])->take(2)->join('') }}</span><div><h2>{{ $user->name }}</h2><p>{{ $user->job_title ?: 'Learner' }}@if($user->company) · {{ $user->company }}@endif</p></div></div>
<form class="form-grid profile-form" method="POST" action="/profile">@csrf @method('PUT')
<label>Full name<input class="form-control" name="name" value="{{ old('name',$user->name) }}" required></label><label>Email address<input class="form-control" type="email" name="email" value="{{ old('email',$user->email) }}" required></label><label>Mobile number<input class="form-control" name="mobile" value="{{ old('mobile',$user->mobile) }}" placeholder="+91..."></label><label>Job title<input class="form-control" name="job_title" value="{{ old('job_title',$user->job_title) }}"></label><label class="full">Company<input class="form-control" name="company" value="{{ old('company',$user->company) }}"></label>
<div class="profile-location-fields full"><label>Country<select class="form-select" name="country_id" id="countrySelect" required><option value="">Select country</option>@foreach($countries as $country)<option value="{{ $country->id }}" @selected((int)old('country_id',$user->country_id)===$country->id)>{{ $country->name }}</option>@endforeach</select></label><label>State<select class="form-select" name="state_id" id="stateSelect" required><option value="">Select state</option>@foreach($states as $state)<option value="{{ $state->id }}" @selected((int)old('state_id',$user->state_id)===$state->id)>{{ $state->name }}</option>@endforeach</select></label><label>City<select class="form-select" name="city_id" id="citySelect"><option value="">Select city</option>@foreach($cities as $city)<option value="{{ $city->id }}" @selected((int)old('city_id',$user->city_id)===$city->id)>{{ $city->name }}</option>@endforeach</select></label></div>
<label class="full">Bio<textarea class="form-control" name="bio" rows="4">{{ old('bio',$user->bio) }}</textarea></label><div class="full d-flex justify-content-end"><button class="btn btn-gradient"><i class="bi bi-check2"></i> Save profile</button></div></form></section>
<aside class="profile-aside"><div class="panel-card"><h3>Account details</h3><div class="profile-detail"><i class="bi bi-envelope"></i><span><small>Email</small><strong>{{ $user->email }}</strong></span></div><div class="profile-detail"><i class="bi bi-geo-alt"></i><span><small>Location</small><strong>{{ collect([$user->city?->name,$user->state?->name,$user->country?->name])->filter()->join(', ') ?: 'Not provided' }}</strong></span></div><div class="profile-detail"><i class="bi bi-shield-check"></i><span><small>Account status</small><strong>{{ ucfirst($user->status ?? 'active') }}</strong></span></div><div class="profile-detail"><i class="bi bi-calendar3"></i><span><small>Member since</small><strong>{{ $user->created_at->format('M Y') }}</strong></span></div></div>@if($user->signupAnswers->count())<div class="panel-card mt-3"><h3>Registration answers</h3>@foreach($user->signupAnswers as $answer)<div class="answer-row"><small>{{ $answer->field?->label }}</small><strong>{{ is_array(json_decode($answer->value,true)) ? collect(json_decode($answer->value,true))->join(', ') : $answer->value }}</strong></div>@endforeach</div>@endif</aside>
</div>
@endsection
