@extends('layouts.portal')
@section('title',$poll->exists?'Edit Poll':'Add Poll')
@section('content')
<div class="page-heading"><div><span class="eyebrow">POLL MODULE</span><h1>{{ $poll->exists?'Edit poll':'Add poll' }}</h1><p>Selecting a webinar keeps this poll separate from every other client.</p></div><a class="btn btn-light" href="{{ route('admin.polls.index') }}">Back</a></div>
@if($errors->any())<div class="alert alert-danger"><ul class="mb-0">@foreach($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></div>@endif
@php($answers=old('answers',$poll->exists?$poll->options->pluck('label')->all():['','','','']))
@php($correctIndex=old('correct_index',$poll->exists?$poll->options->search(fn($option)=>$option->is_correct):null))
@php($pollType=old('type',$correctIndex!==null && $correctIndex!==false?'quiz':'poll'))
@php($hasVotes=$poll->exists && $poll->options->contains(fn($option)=>$option->responses()->exists()))
@if($hasVotes)<div class="alert alert-warning"><i class="bi bi-exclamation-triangle"></i> Voting has started. Answer text, removal, and the correct answer are locked to protect existing results.</div>@endif
<form class="panel-card form-panel" method="POST" action="{{ $poll->exists?route('admin.polls.update',$poll):route('admin.polls.store') }}">@csrf @if($poll->exists)@method('PUT')@endif
<div class="form-grid">
<label class="full">Webinar / Event<select class="form-select" name="webinar_id" required><option value="">Choose webinar</option>@foreach($webinars as $webinar)<option value="{{ $webinar->id }}" @selected(old('webinar_id',$poll->webinar_id)==$webinar->id)>{{ $webinar->title }}</option>@endforeach</select></label>
<label class="full">Engagement type<select class="form-select" name="type" id="pollType" required @disabled($hasVotes)><option value="poll" @selected($pollType==='poll')>Poll — collect audience opinion</option><option value="quiz" @selected($pollType==='quiz')>Quiz — one answer is correct</option></select>@if($hasVotes)<input type="hidden" name="type" value="{{ $pollType }}">@endif<small class="text-muted">Quiz mode lets you mark the correct option and reveal it live through Reverb when “Show correct answer” is enabled in Live Control.</small></label>
<label class="full" id="answerRevealField">Correct answer visibility<select class="form-select" name="answer_reveal" id="answerReveal"><option value="immediate" @selected(old('answer_reveal',$poll->answer_reveal)==='immediate')>Show immediately after attendee answers</option><option value="after_webinar" @selected(old('answer_reveal',$poll->answer_reveal ?: 'after_webinar')==='after_webinar')>Show after the webinar finishes</option><option value="never" @selected(old('answer_reveal',$poll->answer_reveal)==='never')>Don't show the correct answer</option></select><small class="text-muted">Quiz vote percentages stay hidden in every mode. This setting controls only when the correct answer is highlighted.</small></label>
<label class="full">Question<input class="form-control" name="question" value="{{ old('question',$poll->question) }}" required></label>
<div class="full"><div class="panel-title mb-2"><div><strong>Options</strong><small class="d-block text-muted" id="pollOptionsHelp">{{ $pollType==='quiz'?'Choose the one correct answer.':'Add the choices your audience can vote for.' }}</small></div><button type="button" class="btn btn-sm btn-light" id="addPollAnswer" @disabled($hasVotes)><i class="bi bi-plus"></i> Add option</button></div>
<div id="pollAnswers" class="answer-builder">@foreach($answers as $index=>$answer)<div class="answer-row" data-option-row><input class="form-control" name="answers[]" value="{{ $answer }}" placeholder="Option text" required @readonly($hasVotes)><label class="form-check text-nowrap ms-2" data-correct-answer><input class="form-check-input" type="radio" name="correct_index" value="{{ $index }}" @checked((string)$correctIndex===(string)$index) @disabled($hasVotes)> Correct</label><button type="button" class="answer-delete-btn remove-poll-answer" title="Delete option" @disabled($hasVotes)><i class="bi bi-trash3"></i></button></div>@endforeach</div>
@if($hasVotes && $pollType==='quiz')<input type="hidden" name="correct_index" value="{{ $correctIndex }}">@endif
</div>
<label>Start date/time<input class="form-control" type="datetime-local" name="started_at" value="{{ old('started_at',$poll->started_at?->format('Y-m-d\\TH:i')) }}"></label>
<label>End date/time<input class="form-control" type="datetime-local" name="ended_at" value="{{ old('ended_at',$poll->ended_at?->format('Y-m-d\\TH:i')) }}"></label>
<label>Status<select class="form-select" name="status">@foreach(['draft'=>'Draft','active'=>'Published / Active','ended'=>'Ended','hidden'=>'Hidden'] as $value=>$label)<option value="{{ $value }}" @selected(old('status',$poll->status??'draft')===$value)>{{ $label }}</option>@endforeach</select></label>
</div><button class="btn btn-light mt-4" name="status" value="draft">Save Draft</button> <button class="btn btn-gradient mt-4" name="status" value="active">{{ $poll->exists?'Save & Publish':'Publish Poll' }}</button></form>
<template id="pollAnswerTemplate"><div class="answer-row" data-option-row><input class="form-control" name="answers[]" placeholder="Option text" required><label class="form-check text-nowrap ms-2" data-correct-answer><input class="form-check-input" type="radio" name="correct_index"> Correct</label><button type="button" class="answer-delete-btn remove-poll-answer"><i class="bi bi-trash3"></i></button></div></template>
<script>document.addEventListener('DOMContentLoaded',()=>{const list=document.getElementById('pollAnswers'),template=document.getElementById('pollAnswerTemplate'),type=document.getElementById('pollType'),help=document.getElementById('pollOptionsHelp'),revealField=document.getElementById('answerRevealField'),reveal=document.getElementById('answerReveal');function reindex(){list.querySelectorAll('[data-option-row]').forEach((row,index)=>row.querySelector('[name=correct_index]').value=index)}function syncType(){const quiz=type.value==='quiz';list.querySelectorAll('[data-correct-answer]').forEach(label=>{label.hidden=!quiz;label.querySelector('input').required=quiz});revealField.hidden=!quiz;reveal.disabled=!quiz;if(!quiz)list.querySelectorAll('[name=correct_index]').forEach(input=>input.checked=false);help.textContent=quiz?'Choose the one correct answer.':'Add the choices your audience can vote for.'}document.getElementById('addPollAnswer')?.addEventListener('click',()=>{list.append(template.content.cloneNode(true));reindex();syncType()});list.addEventListener('click',event=>{if(event.target.closest('.remove-poll-answer')&&list.children.length>2){event.target.closest('[data-option-row]').remove();reindex()}});type.addEventListener('change',syncType);reindex();syncType()});</script>
@endsection
