@extends('layouts.portal')
@section('title',$poll->exists?'Edit Poll':'Add Poll')
@section('content')
<div class="page-heading"><div><span class="eyebrow">POLL MODULE</span><h1>{{ $poll->exists?'Edit poll':'Add poll' }}</h1><p>Selecting a webinar keeps this poll separate from every other client.</p></div><a class="btn btn-light" href="{{ route('admin.polls.index') }}">Back</a></div>
@if($errors->any())<div class="alert alert-danger"><ul class="mb-0">@foreach($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></div>@endif
@php($answers=old('answers',$poll->exists?$poll->options->pluck('label')->all():['','']))
<form class="panel-card form-panel" method="POST" action="{{ $poll->exists?route('admin.polls.update',$poll):route('admin.polls.store') }}">@csrf @if($poll->exists)@method('PUT')@endif<div class="form-grid"><label class="full">Webinar / client<select class="form-select" name="webinar_id" required><option value="">Choose webinar</option>@foreach($webinars as $webinar)<option value="{{ $webinar->id }}" @selected(old('webinar_id',$poll->webinar_id)==$webinar->id)>{{ $webinar->title }}</option>@endforeach</select></label><label class="full">Question<input class="form-control" name="question" value="{{ old('question',$poll->question) }}" required></label><div class="full"><div class="panel-title mb-2"><div><strong>Answers</strong><small class="d-block text-muted">Minimum two answers are required.</small></div><button type="button" class="btn btn-sm btn-light" id="addPollAnswer"><i class="bi bi-plus"></i> Add answer</button></div><div id="pollAnswers" class="answer-builder">@foreach($answers as $answer)<div class="answer-row"><input class="form-control" name="answers[]" value="{{ $answer }}" placeholder="Answer text" required><button type="button" class="answer-delete-btn remove-poll-answer" title="Delete answer" aria-label="Delete answer"><i class="bi bi-trash3"></i></button></div>@endforeach</div></div><label class="setting-toggle full poll-multiple-toggle"><span><strong>Multiple answers</strong><small>Attendee can select more than one answer.</small></span><input type="checkbox" name="allow_multiple" value="1" @checked(old('allow_multiple',$poll->allow_multiple))></label></div><button class="btn btn-gradient mt-4">{{ $poll->exists?'Save poll':'Add poll' }}</button></form>
<template id="pollAnswerTemplate"><div class="answer-row"><input class="form-control" name="answers[]" placeholder="Answer text" required><button type="button" class="answer-delete-btn remove-poll-answer" title="Delete answer" aria-label="Delete answer"><i class="bi bi-trash3"></i></button></div></template>
@endsection
