@extends('layouts.portal')
@section('title','Polls')
@section('content')
@php($isSuperAdmin=auth()->user()->hasRole('super-admin'))
<div class="page-heading"><div><span class="eyebrow">ENGAGEMENT</span><h1>Webinar polls</h1><p>Every poll belongs to one webinar and its client audience only.</p></div>@if($isSuperAdmin || auth()->user()->hasPermission('polls.create'))<a class="btn btn-gradient" href="{{ route('admin.polls.create', ['webinar_id'=>$selectedWebinarId]) }}"><i class="bi bi-plus"></i> Add poll</a>@endif</div>
@if(session('status'))<div class="alert alert-success">{{ session('status') }}</div>@endif
<x-admin-webinar-filter :webinars="$webinars" :selected="$selectedWebinarId" :search="$search" placeholder="Search polls by question..." />
<div class="panel-card table-responsive"><table class="premium-table"><thead><tr><th>Question</th><th>Event / Webinar</th><th>Type</th><th>Options</th><th>Votes</th><th>Status</th><th>Created</th><th>Actions</th></tr></thead><tbody>
@forelse($polls as $poll)<tr><td><strong>{{ $poll->question }}</strong></td><td>{{ $poll->webinar->title }}</td><td><span class="badge text-bg-{{ $poll->type==='Quiz'?'success':'secondary' }}">{{ $poll->type }}</span></td><td>{{ $poll->options_count }}</td><td>{{ $poll->votes_count }}</td><td><span class="status-badge {{ $poll->status==='active'?'live':($poll->status==='ended'?'completed':'scheduled') }}">{{ strtoupper($poll->status) }}</span></td><td>{{ $poll->created_at->format('d M Y') }}</td><td><div class="dropdown poll-action-dropdown"><button class="btn btn-sm btn-light dropdown-toggle" data-bs-toggle="dropdown">Actions</button><div class="dropdown-menu dropdown-menu-end"><a class="dropdown-item" href="{{ route('admin.polls.show',$poll) }}">View / Results</a>@if($isSuperAdmin || auth()->user()->hasPermission('polls.edit'))<a class="dropdown-item" href="{{ route('admin.polls.edit',$poll) }}">Edit</a>@endif @if($isSuperAdmin || auth()->user()->hasPermission('polls.manage')) @if($poll->status==='active')<form method="POST" action="{{ route('admin.polls.status',$poll) }}">@csrf @method('PATCH')<input type="hidden" name="status" value="ended"><button class="dropdown-item text-warning"><i class="bi bi-stop-circle me-1"></i> Stop Poll</button></form>@else<form method="POST" action="{{ route('admin.polls.status',$poll) }}">@csrf @method('PATCH')<input type="hidden" name="status" value="active"><button class="dropdown-item text-success"><i class="bi bi-play-circle me-1"></i> Start Poll</button></form>@endif @endif @if($isSuperAdmin || auth()->user()->hasPermission('polls.create'))<form method="POST" action="{{ route('admin.polls.duplicate',$poll) }}">@csrf<button class="dropdown-item">Duplicate</button></form>@endif @if($isSuperAdmin || auth()->user()->hasPermission('polls.delete'))<form method="POST" action="{{ route('admin.polls.destroy',$poll) }}">@csrf @method('DELETE')<button class="dropdown-item text-danger">Delete</button></form>@endif</div></div></td></tr>
@empty<tr><td colspan="8" class="text-center text-muted py-5">No polls added for this webinar.</td></tr>@endforelse
</tbody></table></div><x-admin-pagination :paginator="$polls" />
@endsection
