@extends('layouts.portal')
@section('title','Polls')
@section('content')
<div class="page-heading"><div><span class="eyebrow">ENGAGEMENT</span><h1>Webinar polls</h1><p>Every poll belongs to one webinar and its client audience only.</p></div><a class="btn btn-gradient" href="{{ route('admin.polls.create', ['webinar_id'=>$selectedWebinarId]) }}"><i class="bi bi-plus"></i> Add poll</a></div>
@if(session('status'))<div class="alert alert-success">{{ session('status') }}</div>@endif
<form class="filter-bar mb-4" method="GET"><select class="form-select" name="webinar_id" onchange="this.form.submit()"><option value="">All webinars</option>@foreach($webinars as $webinar)<option value="{{ $webinar->id }}" @selected($selectedWebinarId===$webinar->id)>{{ $webinar->title }}</option>@endforeach</select></form>
<div class="panel-card table-responsive"><table class="premium-table"><thead><tr><th>Webinar / client</th><th>Question</th><th>Answers</th><th>Status</th><th>Controls</th></tr></thead><tbody>
@forelse($polls as $poll)<tr><td><strong>{{ $poll->webinar->title }}</strong><br><small class="text-muted">{{ route('webinars.show',$poll->webinar) }}</small></td><td>{{ $poll->question }}</td><td>{{ $poll->options->count() }}</td><td><span class="status-badge {{ $poll->status==='active'?'live':($poll->status==='ended'?'completed':'scheduled') }}">{{ strtoupper($poll->status) }}</span></td><td><div class="dropdown poll-action-dropdown"><button class="btn btn-sm btn-light dropdown-toggle" type="button" data-bs-toggle="dropdown" aria-expanded="false">Actions</button><div class="dropdown-menu dropdown-menu-end"><a class="dropdown-item" href="{{ route('admin.polls.show',$poll) }}"><i class="bi bi-bar-chart-fill"></i> Show results</a><a class="dropdown-item" href="{{ route('admin.polls.edit',$poll) }}"><i class="bi bi-pencil"></i> Edit</a><div class="dropdown-divider"></div>@foreach(['active'=>['Start','play-fill'],'ended'=>['Stop','stop-fill'],'hidden'=>['Hide','eye-slash']] as $status=>[$label,$icon])<form method="POST" action="{{ route('admin.polls.status',$poll) }}">@csrf @method('PATCH')<input type="hidden" name="status" value="{{ $status }}"><button class="dropdown-item" @disabled($poll->status===$status)><i class="bi bi-{{ $icon }}"></i> {{ $label }}</button></form>@endforeach<div class="dropdown-divider"></div><form method="POST" action="{{ route('admin.polls.destroy',$poll) }}" onsubmit="return confirm('Delete this poll?')">@csrf @method('DELETE')<button class="dropdown-item text-danger"><i class="bi bi-trash3"></i> Delete</button></form></div></div></td></tr>
@empty<tr><td colspan="5" class="text-center text-muted py-5">No polls added for this webinar.</td></tr>@endforelse
</tbody></table></div><div class="mt-3">{{ $polls->links() }}</div>
@endsection
