@extends('layouts.app')
@php($isRegister = $mode === 'register') @php($isForgot = $mode === 'forgot') @php($isStaff = in_array($mode, ['admin','subadmin'])) @php($emailEnabled=$isStaff || (($locationSettings['registration_email_enabled']??'1')==='1')) @php($mobileEnabled=$isStaff || (($locationSettings['registration_mobile_enabled']??'1')==='1')) @php($passwordEnabled=$isStaff || (($locationSettings['registration_password_enabled']??'1')==='1'))
@section('title', $isRegister ? 'Create account' : ($isForgot ? 'Reset password' : 'Sign in'))
@section('shell')<div class="auth-shell"><div class="auth-showcase"><x-site-brand light /><div class="auth-message"><span class="hero-kicker dark"><i class="bi bi-stars"></i> Knowledge without boundaries</span><h1>{{ $isStaff ? 'Lead every event with confidence.' : 'Ideas become impact when we learn together.' }}</h1><p>Connect with experts, discover practical insights, and grow with a community that believes in lifelong learning.</p><blockquote>“The sessions are thoughtfully curated and immediately useful.” <strong>— John Anderson</strong></blockquote></div><div class="auth-glow"></div></div><div class="auth-panel"><div class="auth-card"><x-site-brand class="d-lg-none mb-5" /><span class="auth-icon"><i class="bi bi-{{ $isRegister ? 'person-plus' : ($isForgot ? 'key' : 'shield-lock') }}"></i></span><h2>{{ $isRegister ? 'Create your account' : ($isForgot ? 'Forgot your password?' : ($isStaff ? 'Welcome to the control center' : 'Welcome back')) }}</h2><p>{{ $isForgot ? 'Enter your email and we’ll send you reset instructions.' : 'Enter your details to continue your learning journey.' }}</p>
@if(session('status'))<div class="alert alert-success">{{ session('status') }}</div>@endif
@if($errors->any())<div class="alert alert-danger">{{ $errors->first() }}</div>@endif
<form method="POST" action="{{ $isRegister ? '/register' : ($isForgot ? '/forgot-password' : ($mode === 'admin' ? '/admin/login' : ($mode === 'subadmin' ? '/sub-admin/login' : '/login'))) }}"><div class="row g-3">@csrf
@if(!$isRegister && !$isForgot && request()->filled('return_to'))<input type="hidden" name="return_to" value="{{ request('return_to') }}">@endif
@if($isRegister)<div class="col-12"><label>Full name</label><div class="input-icon"><i class="bi bi-person"></i><input class="form-control" name="name" value="{{ old('name') }}" placeholder="John Anderson" required></div></div>@endif
@if(!$isRegister || $emailEnabled)<div class="col-12"><label>Email address</label><div class="input-icon"><i class="bi bi-envelope"></i><input class="form-control" name="{{ (!$isRegister && !$isForgot) ? 'login' : 'email' }}" type="email" value="{{ old((!$isRegister && !$isForgot) ? 'login' : 'email') }}" placeholder="you@example.com" @if(!$isRegister || ($locationSettings['registration_email_required']??'1')==='1') required @endif autocomplete="email"></div></div>@endif
@if($isRegister)
@if(($locationSettings['registration_mobile_enabled'] ?? '1') === '1')<div class="col-12"><label>Mobile number</label><div class="input-icon"><i class="bi bi-phone"></i><input class="form-control" name="mobile" value="{{ old('mobile') }}" placeholder="+91 98765 43210" @if(($locationSettings['registration_mobile_required']??'0')==='1') required @endif autocomplete="tel"></div></div>@endif
@if(($locationSettings['registration_country_enabled'] ?? '1') === '1')<div class="col-md-6"><label>Country</label><select class="form-select" name="country_id" id="countrySelect" required><option value="">Select country</option>@foreach($countries as $country)<option value="{{ $country->id }}" @selected((int)old('country_id',(int)($locationSettings['registration_default_country_id']??0))===$country->id)>{{ $country->name }}</option>@endforeach</select></div>@endif
@if(($locationSettings['registration_state_enabled'] ?? '1') === '1')<div class="col-md-6"><label>State</label><select class="form-select" name="state_id" id="stateSelect" required><option value="">Select state</option>@foreach($states as $state)<option value="{{ $state->id }}" @selected((int)old('state_id',(int)($locationSettings['registration_default_state_id']??0))===$state->id)>{{ $state->name }}</option>@endforeach</select></div>@endif
@if(($locationSettings['registration_city_enabled'] ?? '1') === '1')<div class="col-12"><label>City</label><select class="form-select" name="city_id" id="citySelect" required><option value="">Select city</option>@foreach($cities as $city)<option value="{{ $city->id }}" @selected((int)old('city_id')===$city->id)>{{ $city->name }}</option>@endforeach</select></div>@endif
@foreach($signupFields as $field)<div class="col-12 custom-field"><label>{{ $field->label }} @if($field->is_required)<span class="text-danger">*</span>@endif</label>
@if($field->field_type==='text')<input class="form-control" name="custom[{{ $field->id }}]" value="{{ old('custom.'.$field->id) }}" placeholder="{{ $field->placeholder }}" @required($field->is_required)>
@elseif($field->field_type==='dropdown')<select class="form-select" name="custom[{{ $field->id }}]" @required($field->is_required)><option value="">Select {{ strtolower($field->label) }}</option>@foreach($field->options as $option)<option value="{{ $option->value }}" @selected(old('custom.'.$field->id)===$option->value)>{{ $option->label }}</option>@endforeach</select>
@elseif($field->field_type==='radio')<div class="choice-group">@foreach($field->options as $option)<label><input type="radio" name="custom[{{ $field->id }}]" value="{{ $option->value }}" @checked(old('custom.'.$field->id)===$option->value) @required($field->is_required)> {{ $option->label }}</label>@endforeach</div>
@else<div class="choice-group">@foreach($field->options as $option)<label><input type="checkbox" name="custom[{{ $field->id }}][]" value="{{ $option->value }}" @checked(in_array($option->value,old('custom.'.$field->id,[])))> {{ $option->label }}</label>@endforeach</div>@endif
@if($field->help_text)<small class="text-muted">{{ $field->help_text }}</small>@endif</div>@endforeach
@endif
@if(!$isForgot && $passwordEnabled)<div class="col-12"><div class="d-flex justify-content-between"><label>Password</label>@if(!$isRegister)<a href="/forgot-password">Forgot password?</a>@endif</div><div class="input-icon password-field"><i class="bi bi-lock"></i><input class="form-control" name="password" type="password" placeholder="Enter your password" @if(!$isRegister || ($locationSettings['registration_password_required']??'1')==='1') required @endif autocomplete="{{ $isRegister ? 'new-password' : 'current-password' }}"><button type="button" class="password-toggle"><i class="bi bi-eye"></i></button></div></div>@endif
@if($isRegister)@if(($locationSettings['registration_password_enabled'] ?? '1') === '1')<div class="col-12"><label>Confirm password</label><div class="input-icon"><i class="bi bi-lock"></i><input class="form-control" name="password_confirmation" type="password" @if(($locationSettings['registration_password_required']??'1')==='1') required @endif></div></div>@endif<div class="col-12"><label class="form-check-label"><input type="checkbox" class="form-check-input me-2" required> I agree to the Terms and Privacy Policy</label></div>@endif
<div class="col-12"><button class="btn btn-gradient w-100 py-3">{{ $isRegister ? 'Create free account' : ($isForgot ? 'Send reset link' : 'Sign in securely') }} <i class="bi bi-arrow-right"></i></button></div></div></form>
@if(!$isStaff && !$isForgot)<div class="auth-switch">{{ $isRegister ? 'Already have an account?' : 'New to '.($siteSettings['site_name']??'Webinarly').'?' }} <a href="{{ $isRegister ? '/login' : '/register' }}">{{ $isRegister ? 'Sign in' : 'Create free account' }}</a></div>@endif
</div></div></div>@endsection
