@extends('layouts.portal')
@section('title','Admin Dashboard')
@section('content')
<div class="page-heading"><div><span class="eyebrow">{{ $subadmin?'ASSIGNED EVENTS':'GLOBAL OVERVIEW' }}</span><h1>Dashboard</h1><p>{{ $subadmin?'Live totals for webinars assigned to you.':'Live platform totals calculated from backend data.' }}</p></div>@unless($subadmin)<a href="{{ route('admin.webinars.create') }}" class="btn btn-gradient"><i class="bi bi-plus-lg"></i> Create webinar</a>@endunless</div>
<div class="stats-grid dashboard-metric-grid"><x-stat-card label="Events" :value="$webinars->count()" icon="calendar-event" meta="Total webinars" /><x-stat-card label="Registered users" :value="$registeredUsers" icon="people" tone="purple" meta="All registrations" /><x-stat-card label="New today" :value="$todayRegistrations" icon="person-plus" tone="orange" meta="Today's growth" /><x-stat-card label="Total attendees" :value="$totalAttendees" icon="person-check" tone="blue" meta="Joined sessions" /><x-stat-card label="Live now" :value="$liveNow" icon="broadcast" tone="green" :live="true" meta="Active webinars" /><x-stat-card label="Chat threads" :value="$chatMessages" icon="chat-dots" tone="blue" meta="Messages received" /><x-stat-card label="Questions" :value="$questionsCount" icon="question-circle" tone="orange" meta="Audience questions" /><x-stat-card label="Polls" :value="$pollsCount" icon="bar-chart" tone="red" meta="Created polls" /><x-stat-card label="Poll voters" :value="$pollVoters" icon="check2-square" tone="green" meta="Unique voters" /><x-stat-card label="Votes submitted" :value="$votesCount" icon="ui-checks-grid" tone="purple" meta="Total responses" /></div>
<section class="panel-card mt-4"><div class="panel-title"><div><span class="eyebrow">COMMAND CENTER</span><h3>Operational attention</h3><p>Live backend checks that may need an administrator.</p></div></div><div class="stats-grid"><x-stat-card label="Starting in 24h" :value="$upcomingSoon" icon="clock" tone="blue" /><x-stat-card label="Waitlisted" :value="$waitlistCount" icon="hourglass-split" tone="orange" /><x-stat-card label="Certificates pending" :value="$pendingCertificates" icon="patch-check" tone="purple" /><x-stat-card label="Missing video" :value="$missingVideo" icon="camera-video-off" tone="red" /></div></section>
@php
    $regCoords=$chart->map(fn($row,$i)=>[60+$i*108,220-($row['registrations']/$maxChart)*170])->values();
    $attCoords=$chart->map(fn($row,$i)=>[60+$i*108,220-($row['attendees']/$maxChart)*170])->values();
    $smoothPath=function($points){ if($points->isEmpty()) return ''; $path='M '.$points[0][0].' '.$points[0][1]; for($i=1;$i<$points->count();$i++){ $prev=$points[$i-1]; $now=$points[$i]; $midX=($prev[0]+$now[0])/2; $path.=' C '.$midX.' '.$prev[1].', '.$midX.' '.$now[1].', '.$now[0].' '.$now[1]; } return $path; };
    $regPath=$smoothPath($regCoords); $attPath=$smoothPath($attCoords);
@endphp
<div class="dashboard-main-grid mt-4"><section class="panel-card pro-chart-card"><div class="pro-chart-head"><div><span class="pro-chart-kicker"><i class="bi bi-activity"></i> AUDIENCE ANALYTICS</span><h3>Growth & attendance</h3><p>Last 7 days performance</p></div><div class="pro-chart-totals"><span><i class="blue"></i><small>Registrations</small><strong>{{ $chart->sum('registrations') }}</strong></span><span><i class="green"></i><small>Attendees</small><strong>{{ $chart->sum('attendees') }}</strong></span></div></div><div class="dashboard-line-chart pro-line-chart"><div class="chart-scale">@foreach([100,75,50,25,0] as $scale)<span>{{ round($maxChart*$scale/100) }}</span>@endforeach</div><svg viewBox="0 0 760 255" preserveAspectRatio="none"><defs><linearGradient id="proBlueArea" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stop-color="#6366f1" stop-opacity=".3"/><stop offset="1" stop-color="#6366f1" stop-opacity="0"/></linearGradient><linearGradient id="proGreenArea" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stop-color="#14b8a6" stop-opacity=".18"/><stop offset="1" stop-color="#14b8a6" stop-opacity="0"/></linearGradient><filter id="proGlow"><feGaussianBlur stdDeviation="3" result="blur"/><feMerge><feMergeNode in="blur"/><feMergeNode in="SourceGraphic"/></feMerge></filter></defs>@foreach([50,92.5,135,177.5,220] as $y)<line x1="60" y1="{{ $y }}" x2="708" y2="{{ $y }}" class="pro-grid-line"/>@endforeach<path d="{{ $regPath }} L 708 220 L 60 220 Z" fill="url(#proBlueArea)"/><path d="{{ $attPath }} L 708 220 L 60 220 Z" fill="url(#proGreenArea)"/><path d="{{ $regPath }}" class="pro-data-line pro-registration-line"/><path d="{{ $attPath }}" class="pro-data-line pro-attendance-line"/>@foreach($chart as $row)<g class="pro-chart-point"><circle cx="{{ $regCoords[$loop->index][0] }}" cy="{{ $regCoords[$loop->index][1] }}" r="5" class="pro-dot pro-reg-dot"/><title>{{ $row['label'] }} · {{ $row['registrations'] }} registrations</title></g><g class="pro-chart-point"><circle cx="{{ $attCoords[$loop->index][0] }}" cy="{{ $attCoords[$loop->index][1] }}" r="5" class="pro-dot pro-att-dot"/><title>{{ $row['label'] }} · {{ $row['attendees'] }} attendees</title></g>@endforeach</svg><div class="line-chart-labels">@foreach($chart as $row)<span>{{ $row['label'] }}</span>@endforeach</div></div></section><aside class="panel-card"><div class="panel-title"><h3>Engagement summary</h3></div><div class="engagement-list"><div><span>Registrations</span><strong>{{ $totalRegistrations }}</strong></div><div><span>Chat messages</span><strong>{{ $chatMessages }}</strong></div><div><span>Questions asked</span><strong>{{ $questionsCount }}</strong></div><div><span>Total watch time</span><strong>{{ number_format($watchSeconds/3600,1) }} hrs</strong></div><div><span>Attendance rate</span><strong>{{ $totalRegistrations?round(($totalAttendees/$totalRegistrations)*100):0 }}%</strong></div></div></aside></div>
<div class="dashboard-bottom-grid mt-4">
    <section class="panel-card">
        <div class="panel-title">
            <div><h3>Webinar performance</h3><p>Registration and engagement per event</p></div>
            @if($subadmin)
                <a href="{{ route('subadmin.chats.index') }}">Open assigned chats</a>
            @else
                <a href="{{ route('admin.webinars.index') }}">View all</a>
            @endif
        </div>
        <div class="table-responsive"><table class="premium-table"><thead><tr><th>Webinar</th><th>Registered</th><th>Attended</th><th>Polls</th><th>Votes</th><th>Status</th></tr></thead><tbody>@forelse($eventPerformance as $row)<tr><td><strong>{{ $row['webinar']->title }}</strong></td><td>{{ $row['webinar']->registrations_count }}</td><td>{{ $row['attendees'] }}</td><td>{{ $row['webinar']->polls_count }}</td><td>{{ $row['votes'] }}</td><td><span class="status-badge {{ $row['webinar']->status }}">{{ ucfirst($row['webinar']->status) }}</span></td></tr>@empty<tr><td colspan="6" class="text-center text-muted">No webinars found.</td></tr>@endforelse</tbody></table></div>
    </section>
    <aside class="panel-card">
        <div class="panel-title">
            <div><h3>Recent registrations</h3><p>Latest learners</p></div>
            @unless($subadmin)
                <a href="{{ route('admin.registrations') }}">View users</a>
            @endunless
        </div>
        <div class="recent-registration-list">@forelse($recentRegistrations as $registration)<div><span class="avatar">{{ Str::of($registration->user?->name??$registration->email)->substr(0,2)->upper() }}</span><span><strong>{{ $registration->user?->name??$registration->email }}</strong><small>{{ $registration->webinar?->title }} · {{ $registration->registered_at?->diffForHumans() }}</small></span></div>@empty<p class="text-muted">No registrations yet.</p>@endforelse</div>
    </aside>
</div>
@endsection
