@extends('layouts.portal')
@section('title',$field->exists?'Edit Registration Field':'Add Registration Field')
@section('content')
<style>.registration-switches{grid-template-columns:repeat(2,minmax(0,1fr));gap:14px}.registration-switches>label{position:relative;flex-direction:row!important;min-height:78px;padding:16px 18px!important;border:1px solid #e4e7ef!important;background:linear-gradient(145deg,#fff,#f7f8fc)!important;box-shadow:0 7px 18px rgba(15,23,42,.04);transition:.2s}.registration-switches>label:hover{border-color:#c4b5fd!important;transform:translateY(-1px)}.registration-switches>label:has(input:checked){border-color:#8b5cf6!important;background:linear-gradient(145deg,#f5f3ff,#eef2ff)!important}.registration-switches .form-check-input{flex:none;width:46px!important;height:25px!important;margin:0!important;border:0!important;background-color:#cbd5e1;background-position:left center;cursor:pointer}.registration-switches .form-check-input:checked{background-color:#6d28d9;background-position:right center}.registration-switches strong{font-size:.82rem}.registration-switches small{margin-top:3px;font-size:.65rem}@media(max-width:650px){.registration-switches{grid-template-columns:1fr}}</style>
<div class="page-heading"><div><span class="eyebrow">{{ $webinar->title }}</span><h1>{{ $field->exists?'Edit':'Add' }} registration field</h1><p>Use dedicated location selectors for automatic Country → State → City dependency.</p></div></div>
@if($errors->any())<div class="alert alert-danger">{{ $errors->first() }}</div>@endif
<form class="panel-card form-panel" method="POST" action="{{ $field->exists?route('admin.registration.webinar.fields.update',$field):route('admin.registration.webinar.fields.store',$webinar) }}">@csrf @if($field->exists)@method('PUT')@endif
<div class="form-grid">
<label>Field label<input class="form-control" name="label" value="{{ old('label',$field->label) }}" required></label>
<label>Field type<select class="form-select" name="field_type" id="fieldType">@foreach(['text'=>'Text box','password'=>'Password','dropdown'=>'Dropdown','radio'=>'Radio buttons','checkbox'=>'Checkboxes','country'=>'Country selector','state'=>'State selector','city'=>'City selector'] as $value=>$label)<option value="{{ $value }}" @selected(old('field_type',$field->field_type?:'text')===$value)>{{ $label }}</option>@endforeach</select></label>
<label>Icon<select class="form-select" name="icon">@foreach(['input-cursor-text'=>'Text','lock'=>'Password / Lock','person'=>'User','envelope'=>'Email','phone'=>'Phone','building'=>'Building','geo-alt'=>'Location','briefcase'=>'Work','mortarboard'=>'Education'] as $value=>$label)<option value="{{ $value }}" @selected(old('icon',$field->icon?:'input-cursor-text')===$value)>{{ $label }}</option>@endforeach</select></label>
<label>Width<select class="form-select" name="width"><option value="half" @selected(old('width',$field->width)==='half')>Half</option><option value="full" @selected(old('width',$field->width?:'full')==='full')>Full</option></select></label>
<label class="full">Placeholder<input class="form-control" name="placeholder" value="{{ old('placeholder',$field->placeholder) }}" placeholder="Text shown inside the field"></label>
<label class="full {{ in_array(old('field_type',$field->field_type),['dropdown','radio','checkbox'])?'':'d-none' }}" id="optionBuilder">Options (one per line)<textarea class="form-control" name="options" rows="5">{{ old('options',$field->exists?$field->options->pluck('label')->join("\n"):'') }}</textarea></label>
<div class="full p-3 rounded-4 border bg-light-subtle"><div class="d-flex align-items-center gap-2 mb-3"><span class="stat-icon tone-purple"><i class="bi bi-diagram-3"></i></span><div><strong>Conditional visibility</strong><small class="d-block text-muted">Show this field only when another answer matches your rule.</small></div></div><div class="form-grid"><label>Depends on<select class="form-select" name="condition_field_id"><option value="">Always show</option>@foreach(($webinar->registrationForm?->fields ?? collect())->where('id','!=',$field->id) as $candidate)<option value="{{ $candidate->id }}" @selected(old('condition_field_id',$field->condition_field_id)==$candidate->id)>{{ $candidate->label }}</option>@endforeach</select></label><label>Rule<select class="form-select" name="condition_operator"><option value="equals" @selected(old('condition_operator',$field->condition_operator)==='equals')>Answer equals</option><option value="not_equals" @selected(old('condition_operator',$field->condition_operator)==='not_equals')>Answer does not equal</option></select></label><label class="full">Answer value<input class="form-control" name="condition_value" value="{{ old('condition_value',$field->condition_value) }}" placeholder="Example: yes"></label></div></div>
<div class="full registration-switches"><label><span><strong>Required</strong><small>User must complete this field</small></span><input class="form-check-input" type="checkbox" name="is_required" value="1" @checked(old('is_required',$field->is_required))></label><label><span><strong>Login identifier</strong><small>Allow this field for login</small></span><input class="form-check-input" type="checkbox" name="login_enabled" value="1" @checked(old('login_enabled',$field->login_enabled))></label>@if($field->exists)<label><span><strong>Enabled</strong><small>Show this field on registration</small></span><input class="form-check-input" type="checkbox" name="is_enabled" value="1" @checked(old('is_enabled',$field->is_enabled))></label>@endif</div>
</div><div class="d-flex justify-content-end gap-2 mt-4"><a class="btn btn-light" href="{{ route('admin.dynamic-fields.index',['webinar_id'=>$webinar->id]) }}">Cancel</a><button class="btn btn-gradient">Save changes</button></div></form>
@endsection
