@extends('layouts.portal')
@section('title', $title)
@section('content')
<div class="page-heading"><div><span class="eyebrow">ADMIN WORKSPACE</span><h1>{{ $title }}</h1><p>Manage event operations with clear context and confident actions.</p></div><div class="d-flex gap-2"><button class="btn btn-light"><i class="bi bi-download"></i> Export</button>@if(in_array($type,['webinars','speakers','subadmins','notifications']))<a class="btn btn-gradient" href="{{ request()->path() === 'admin/webinars' ? '/admin/webinars/create' : request()->url().'/create' }}"><i class="bi bi-plus-lg"></i> Add new</a>@endif</div></div>
@if(in_array($type, ['webinars','speakers','users','registrations','subadmins','notifications','certificates']))
<div class="filter-bar"><div class="filter-search"><i class="bi bi-search"></i><input data-table-search placeholder="Search {{ strtolower($title) }}..."></div><select><option>All statuses</option><option>Active</option><option>Scheduled</option><option>Completed</option></select><select><option>All events</option><option>Future of AI in Business</option><option>Healthcare Summit</option></select><button class="btn btn-light"><i class="bi bi-sliders"></i> Filters</button></div>
@if($type === 'registrations')<div class="alert alert-info border-0"><i class="bi bi-info-circle me-2"></i><strong>Webinar registrations</strong> appear here after a learner reserves a seat. New platform accounts appear under <a href="/admin/users" class="alert-link">Users</a>.</div>@endif
<div class="panel-card"><div class="table-responsive"><table class="premium-table" id="resourceTable"><thead><tr>@if($type==='webinars')<th><input type="checkbox"></th><th>Webinar</th><th>Speaker</th><th>Date</th><th>Registrations</th><th>Status</th><th>Actions</th>@elseif($type==='subadmins')<th>Name</th><th>Role</th><th>Assigned events</th><th>Permissions</th><th>Last login</th><th>Status</th><th></th>@else<th>Name / Subject</th><th>Email / Type</th><th>Event</th><th>Created</th><th>Status</th><th>Actions</th>@endif</tr></thead><tbody>
@if(isset($databaseRows) && $type === 'users')
@forelse($databaseRows as $user)<tr><td><div class="speaker-line"><span class="mini-avatar">{{ collect(explode(' ', $user->name))->map(fn($part) => $part[0])->take(2)->join('') }}</span><strong>{{ $user->name }}</strong></div></td><td>{{ $user->email }}</td><td>{{ $user->roles->pluck('name')->join(', ') ?: 'Learner' }}</td><td>{{ $user->created_at?->format('M d, Y') }}</td><td><span class="status-badge completed">{{ ucfirst($user->status ?? 'active') }}</span></td><td><a class="icon-btn" href="/admin/users/{{ $user->id }}"><i class="bi bi-eye"></i></a></td></tr>@empty<tr><td colspan="6"><div class="text-center py-5 text-muted"><i class="bi bi-people fs-2 d-block mb-2"></i>No registered users found.</div></td></tr>@endforelse
@elseif(isset($databaseRows) && $type === 'registrations')
@forelse($databaseRows as $registration)<tr><td><div class="speaker-line"><span class="mini-avatar">{{ collect(explode(' ', $registration->user?->name ?? $registration->email))->map(fn($part) => $part[0])->take(2)->join('') }}</span><strong>{{ $registration->user?->name ?? 'Guest attendee' }}</strong></div></td><td>{{ $registration->email }}</td><td>{{ $registration->webinar?->title ?? 'Removed webinar' }}</td><td>{{ $registration->registered_at?->format('M d, Y g:i A') }}</td><td><span class="status-badge {{ $registration->status === 'approved' ? 'completed' : 'scheduled' }}">{{ ucfirst($registration->status) }}</span></td><td><a class="icon-btn" href="{{ route('admin.registrations.show',$registration) }}" title="View audience journey"><i class="bi bi-eye"></i></a></td></tr>@empty<tr><td colspan="6"><div class="text-center py-5 text-muted"><i class="bi bi-person-check fs-2 d-block mb-2"></i>No webinar registrations yet. Reserve a seat from a learner account to create the first one.</div></td></tr>@endforelse
@elseif($type==='webinars')
@foreach([['Future of AI in Business','Dr. Sarah Mitchell','Sep 12 · 4:00 PM','2,846','Live','purple'],['Digital Healthcare Summit','Priya Shah','Sep 18 · 3:30 PM','2,212','Scheduled','blue'],['Growth Marketing Masterclass','Daniel Carter','Sep 24 · 5:00 PM','1,984','Scheduled','orange'],['Building Scalable Digital Products','Michael Thompson','Oct 02 · 2:00 PM','1,442','Draft','green']] as $row)<tr><td><input type="checkbox"></td><td><span class="table-webinar {{ $row[5] }}"><i class="bi bi-camera-video"></i></span><strong>{{ $row[0] }}</strong></td><td>{{ $row[1] }}</td><td>{{ $row[2] }}</td><td>{{ $row[3] }}</td><td><span class="status-badge {{ strtolower($row[4]) }}">{{ $row[4] }}</span></td><td><div class="dropdown"><button class="icon-btn" data-bs-toggle="dropdown"><i class="bi bi-three-dots"></i></button><ul class="dropdown-menu dropdown-menu-end"><li><a class="dropdown-item" href="/admin/webinars/1">View overview</a></li><li><a class="dropdown-item" href="/admin/webinars/1/edit">Edit</a></li><li><a class="dropdown-item" href="/admin/webinars/1/live-control">Live control</a></li><li><button class="dropdown-item text-danger" data-bs-toggle="modal" data-bs-target="#confirmModal">Delete</button></li></ul></div></td></tr>@endforeach
@elseif($type==='subadmins')
@foreach([['Priya Shah','Event Manager','3 events','Webinars, Reports','Today, 10:42 AM'],['Daniel Carter','Content Manager','All events','CMS, Speakers','Yesterday, 5:18 PM'],['Ananya Mehta','Support Lead','2 events','Users, Registrations','Aug 22, 3:12 PM']] as $row)<tr><td><div class="speaker-line"><span class="mini-avatar">{{ substr($row[0],0,1) }}{{ substr(strrchr($row[0],' '),1,1) }}</span><span><strong>{{ $row[0] }}</strong><small>{{ strtolower(str_replace(' ','@',$row[0])) }}.com</small></span></div></td><td>{{ $row[1] }}</td><td>{{ $row[2] }}</td><td>{{ $row[3] }}</td><td>{{ $row[4] }}</td><td><span class="status-badge completed">Active</span></td><td><i class="bi bi-three-dots"></i></td></tr>@endforeach
@else
@foreach([['John Anderson','john@northstar.co','Future of AI in Business','Aug 25, 2026'],['Maya Rodriguez','maya@brightlabs.io','Digital Healthcare Summit','Aug 24, 2026'],['Ethan Williams','ethan@orbitworks.com','Growth Marketing Masterclass','Aug 23, 2026'],['Sophia Chen','sophia@novahealth.com','Future of AI in Business','Aug 22, 2026']] as $row)<tr><td><div class="speaker-line"><span class="mini-avatar">{{ substr($row[0],0,1) }}{{ substr(strrchr($row[0],' '),1,1) }}</span><strong>{{ $row[0] }}</strong></div></td><td>{{ $row[1] }}</td><td>{{ $row[2] }}</td><td>{{ $row[3] }}</td><td><span class="status-badge completed">Active</span></td><td><button class="icon-btn"><i class="bi bi-three-dots"></i></button></td></tr>@endforeach
@endif</tbody></table></div>@if(isset($databaseRows))<div class="pagination-bar"><span>Showing {{ $databaseRows->firstItem() ?? 0 }}–{{ $databaseRows->lastItem() ?? 0 }} of {{ $databaseRows->total() }} results</span>{{ $databaseRows->links() }}</div>@else<nav class="pagination-bar"><span>Showing 1–4 of 128 results</span><div><button disabled><i class="bi bi-chevron-left"></i></button><button class="active">1</button><button>2</button><button>3</button><button><i class="bi bi-chevron-right"></i></button></div></nav>@endif</div>
@elseif($type==='wizard')
<div class="wizard-shell"><aside class="wizard-steps">@foreach(['Basic information','Speaker','Schedule','Media','Live settings','Registration','Engagement','Review & publish'] as $i=>$step)<button class="wizard-step {{ $i===0?'active':'' }}" data-step="{{ $i }}"><span>{{ $i+1 }}</span><div><strong>{{ $step }}</strong><small>{{ $i===0?'In progress':'Complete this step' }}</small></div></button>@endforeach</aside><section class="panel-card wizard-panel"><form id="webinarWizard"><div class="wizard-page active" data-page="0"><span class="eyebrow">STEP 1 OF 8</span><h2>Basic information</h2><p>Give your audience a clear reason to attend.</p><div class="form-grid"><label class="full">Webinar title<input class="form-control" value="{{ str_starts_with($title,'Edit') ? 'Future of AI in Business' : '' }}" placeholder="e.g. Future of AI in Business"></label><label>Category<select class="form-select"><option>Technology & Innovation</option></select></label><label>Language<select class="form-select"><option>English</option><option>Hindi</option></select></label><label class="full">Short description<textarea class="form-control" rows="3" placeholder="A concise summary for webinar cards"></textarea></label><label class="full">Full description<textarea class="form-control" rows="6" placeholder="Tell attendees what they will learn"></textarea></label></div></div>@for($i=1;$i<8;$i++)<div class="wizard-page" data-page="{{ $i }}"><span class="eyebrow">STEP {{ $i+1 }} OF 8</span><h2>{{ ['','Select a speaker','Set the schedule','Add media','Configure the live experience','Registration settings','Engagement tools','Review & publish'][$i] }}</h2><p>Configure this section with event-specific options.</p><div class="drop-zone"><i class="bi bi-{{ $i===2?'calendar3':($i===3?'cloud-arrow-up':'sliders') }}"></i><h4>{{ $i===7?'Everything looks ready':'Premium configuration workspace' }}</h4><p>{{ $i===3?'Drag and drop media here, or browse your device.':'Complete the relevant settings before continuing.' }}</p>@if($i===6)<div class="switch-list"><label>Live chat <input type="checkbox" checked></label><label>Q&A <input type="checkbox" checked></label><label>Polls <input type="checkbox" checked></label><label>Certificates <input type="checkbox" checked></label></div>@endif</div></div>@endfor<div class="wizard-actions"><button type="button" class="btn btn-light" id="wizardBack">Back</button><button type="button" class="btn btn-light ms-auto" data-demo-toast>Save draft</button><button type="button" class="btn btn-gradient" id="wizardNext">Continue <i class="bi bi-arrow-right"></i></button></div></form></section></div>
@elseif($type==='event')
<div class="event-banner"><div><span class="status-badge live">LIVE</span><h2>Future of AI in Business</h2><p><i class="bi bi-calendar3"></i> Sep 12, 2026 · 4:00 PM IST &nbsp; <i class="bi bi-mic"></i> Dr. Sarah Mitchell</p></div><div><a class="btn btn-light" href="/admin/webinars/1/edit">Edit event</a><a class="btn btn-danger" href="/admin/webinars/1/live-control"><i class="bi bi-broadcast"></i> Live control</a></div></div><div class="detail-tabs nav">@foreach(['Overview','Registrations','Attendees','Speakers','Q&A','Polls','Resources','Recordings','Certificates','Analytics'] as $i=>$tab)<button class="{{ $i===0?'active':'' }}">{{ $tab }}</button>@endforeach</div><div class="stats-grid mt-4"><x-stat-card label="Registrations" value="2,846" icon="person-check" /><x-stat-card label="Live attendees" value="1,248" icon="broadcast" tone="red" /><x-stat-card label="Questions" value="186" icon="question-circle" tone="blue" /><x-stat-card label="Engagement" value="92%" icon="heart" tone="green" /></div><div class="panel-card mt-4"><div class="panel-title"><h3>Live engagement pulse</h3><span class="status-badge live">Reverb-ready UI</span></div><div class="chart-shell short"><div class="bars"><i style="height:30%"></i><i style="height:46%"></i><i style="height:58%"></i><i style="height:52%"></i><i style="height:78%"></i><i class="highlight" style="height:92%"></i><i style="height:84%"></i><i style="height:75%"></i></div></div></div>
@elseif($type==='control')
<div class="control-grid"><div class="control-stage"><div class="control-preview"><span class="status-badge live">LIVE · 01:18:42</span><span class="speaker-photo purple">SM</span><h2>Future of AI in Business</h2><p>Dr. Sarah Mitchell is presenting</p></div><div class="d-flex gap-2 mt-3"><button class="btn btn-danger flex-fill" data-bs-toggle="modal" data-bs-target="#confirmModal"><i class="bi bi-stop-circle"></i> End webinar</button><button class="btn btn-light"><i class="bi bi-display"></i> Preview</button></div></div><div><div class="stats-grid control-stats"><x-stat-card label="Current viewers" value="1,248" icon="eye" /><x-stat-card label="Messages/min" value="42" icon="chat" tone="blue" /><x-stat-card label="Questions" value="186" icon="question-circle" tone="orange" /><x-stat-card label="Raised hands" value="28" icon="hand-index" tone="red" /></div><div class="panel-card mt-3"><div class="panel-title"><h3>Moderation controls</h3><span class="connection"><i></i> Connection stable</span></div><div class="switch-list control-switches"><label><span><i class="bi bi-chat"></i> Live chat</span><input type="checkbox" checked></label><label><span><i class="bi bi-question-circle"></i> Q&A</span><input type="checkbox" checked></label><label><span><i class="bi bi-bar-chart"></i> Active poll</span><input type="checkbox"></label><label><span><i class="bi bi-emoji-smile"></i> Reactions</span><input type="checkbox" checked></label></div></div></div></div>
@elseif($type==='reports')
<div class="filter-bar"><select><option>Last 30 days</option></select><select><option>All webinars</option></select><select><option>All speakers</option></select><button class="btn btn-gradient">Apply filters</button></div><div class="stats-grid"><x-stat-card label="Registrations" value="24.8K" /><x-stat-card label="Attendance rate" value="78.4%" tone="green" /><x-stat-card label="Avg. watch time" value="64 min" tone="blue" /><x-stat-card label="Engagement" value="89.2%" tone="orange" /></div><div class="admin-grid mt-4"><div class="panel-card chart-card"><div class="panel-title"><h3>Registration trend</h3></div><div class="chart-shell"><div class="bars"><i style="height:38%"></i><i style="height:52%"></i><i style="height:47%"></i><i style="height:72%"></i><i style="height:64%"></i><i class="highlight" style="height:88%"></i></div></div></div><div class="panel-card"><div class="panel-title"><h3>Engagement distribution</h3></div><div class="donut-wrap"><div class="donut"><span>89%<small>Strong</small></span></div></div></div></div>
@elseif($type==='designer')
<div class="designer-grid"><div class="panel-card"><h3>Certificate settings</h3><div class="form-grid"><label class="full">Template name<input class="form-control" value="Webinar Excellence"></label><label class="full">Headline<input class="form-control" value="Certificate of Completion"></label><label class="full">Signatory<input class="form-control" value="Alex Morgan, Program Director"></label><label>Accent color<input class="form-control form-control-color" type="color" value="#6d28d9"></label></div><button class="btn btn-gradient w-100 mt-4" data-demo-toast>Save template</button></div><div class="certificate-preview"><div class="cert-inner"><span class="brand-mark"><i class="bi bi-camera-video-fill"></i></span><small>WEBINARLY PRESENTS</small><h2>Certificate of Completion</h2><p>This certificate is proudly awarded to</p><h1>John Anderson</h1><p>for successfully completing</p><h3>Future of AI in Business</h3><div class="cert-footer"><span>SEPTEMBER 12, 2026<small>Date</small></span><span class="cert-seal"><i class="bi bi-award"></i></span><span>Alex Morgan<small>Program Director</small></span></div></div></div></div>
@else
<div class="panel-card form-panel"><div class="form-header"><span class="modal-icon"><i class="bi bi-sliders"></i></span><div><h2>{{ $title }}</h2><p>Complete the details below. Changes are demonstrated locally in this UI phase.</p></div></div><form class="form-grid" onsubmit="event.preventDefault()"><label>Full name / Title<input class="form-control" placeholder="Enter a descriptive name"></label><label>Email / Slug<input class="form-control" placeholder="name@company.com"></label><label>Role / Category<select class="form-select"><option>Event Manager</option><option>Content Manager</option></select></label><label>Status<select class="form-select"><option>Active</option><option>Draft</option></select></label><label class="full">Description<textarea class="form-control" rows="5" placeholder="Add context and details"></textarea></label>@if($type==='permissions')<div class="full permission-matrix"><h3>Permission matrix</h3>@foreach(['Webinars','Speakers','Users','Registrations','Reports','Certificates','Notifications'] as $module)<div><strong>{{ $module }}</strong><label><input type="checkbox" checked> View</label><label><input type="checkbox"> Create</label><label><input type="checkbox"> Edit</label><label><input type="checkbox"> Delete / Export</label></div>@endforeach</div>@endif<div class="full d-flex justify-content-end gap-2"><button class="btn btn-light">Cancel</button><button class="btn btn-gradient" data-demo-toast>Save changes</button></div></form></div>
@endif
@endsection
