<?php

use App\Http\Controllers\Admin\ActivityLogController;
use App\Http\Controllers\Admin\AttendanceController;
use App\Http\Controllers\Admin\CertificateController;
use App\Http\Controllers\Admin\ChatController;
use App\Http\Controllers\Admin\EngagementController;
use App\Http\Controllers\Admin\GeneralSettingsController;
use App\Http\Controllers\Admin\NotificationController;
use App\Http\Controllers\Admin\PermissionController;
use App\Http\Controllers\Admin\PollController;
use App\Http\Controllers\Admin\QuestionController;
use App\Http\Controllers\Admin\RegistrationController;
use App\Http\Controllers\Admin\RegistrationSettingsController;
use App\Http\Controllers\Admin\ReportController;
use App\Http\Controllers\Admin\SpeakerController;
use App\Http\Controllers\Admin\SubAdminController;
use App\Http\Controllers\Admin\WebinarController;
use App\Http\Controllers\AuthController;
use App\Http\Controllers\DashboardController;
use App\Http\Controllers\ProfileController;
use App\Models\Banner;
use App\Models\Brand;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Route;

Route::middleware('guest')->group(function () {
    Route::get('/admin/login', [AuthController::class, 'showAdminLogin'])->name('admin.login');
    Route::post('/admin/login', [AuthController::class, 'loginAdmin']);
});

Route::middleware(['auth', 'role:super-admin,sub-admin', 'admin.access'])->group(function () {
    Route::get('/admin/dashboard', [DashboardController::class, 'admin'])->name('admin.dashboard');
    Route::get('/admin/change-password', [ProfileController::class, 'password'])->name('admin.password');
    Route::put('/admin/change-password', [ProfileController::class, 'updatePassword'])->name('admin.password.update');
    Route::get('/admin/profile', [ProfileController::class, 'adminProfile'])->name('admin.profile');
    Route::put('/admin/profile', [ProfileController::class, 'update'])->name('admin.profile.update');
    Route::get('/admin/users', [RegistrationController::class, 'users'])->name('admin.users');
    Route::get('/admin/attendance', [AttendanceController::class, 'index'])->name('admin.attendance');
    Route::get('/admin/attendance/export', [AttendanceController::class, 'export'])->name('admin.attendance.export');
    Route::get('/admin/activity-logs', [ActivityLogController::class, 'index'])->name('admin.activity-logs');
    Route::get('/admin/registrations', [RegistrationController::class, 'index'])->name('admin.registrations');
    Route::get('/admin/registrations/{registration}', [RegistrationController::class, 'show'])->name('admin.registrations.show');
    Route::delete('/admin/registrations/{registration}', [RegistrationController::class, 'destroy'])->name('admin.registrations.destroy');
    Route::get('/admin/registration-settings', [RegistrationSettingsController::class, 'index'])->name('admin.registration-settings');
    Route::get('/admin/dynamic-fields', [RegistrationSettingsController::class, 'index'])->name('admin.dynamic-fields.index');
    Route::get('/admin/registration-settings/{webinar}/preview', [RegistrationSettingsController::class, 'preview'])->name('admin.registration.preview');
    Route::post('/admin/registration-settings', [RegistrationSettingsController::class, 'update']);
    Route::post('/admin/registration-fields', [RegistrationSettingsController::class, 'storeField']);
    Route::patch('/admin/registration-fields/{field}/toggle', [RegistrationSettingsController::class, 'toggleField']);
    Route::delete('/admin/registration-fields/{field}', [RegistrationSettingsController::class, 'destroyField']);
    Route::put('/admin/registration-settings/{webinar}', [RegistrationSettingsController::class, 'updateWebinarForm'])->name('admin.registration.webinar.update');
    Route::put('/admin/registration-settings/{webinar}/fields', [RegistrationSettingsController::class, 'bulkUpdateWebinarFields'])->name('admin.registration.webinar.fields.bulk');
    Route::post('/admin/registration-settings/{webinar}/preset', [RegistrationSettingsController::class, 'applyPreset'])->name('admin.registration.webinar.preset');
    Route::post('/admin/registration-settings/{webinar}/fields', [RegistrationSettingsController::class, 'storeWebinarField'])->name('admin.registration.webinar.fields.store');
    Route::get('/admin/registration-settings/{webinar}/fields/create', [RegistrationSettingsController::class, 'createWebinarField'])->name('admin.registration.webinar.fields.create');
    Route::get('/admin/webinar-registration-fields/{field}/edit', [RegistrationSettingsController::class, 'editWebinarField'])->name('admin.registration.webinar.fields.edit');
    Route::put('/admin/webinar-registration-fields/{field}', [RegistrationSettingsController::class, 'updateWebinarField'])->name('admin.registration.webinar.fields.update');
    Route::patch('/admin/webinar-registration-fields/{field}/toggle', [RegistrationSettingsController::class, 'toggleWebinarField'])->name('admin.registration.webinar.fields.toggle');
    Route::delete('/admin/webinar-registration-fields/{field}', [RegistrationSettingsController::class, 'destroyWebinarField'])->name('admin.registration.webinar.fields.destroy');

    Route::get('/admin/webinars', [WebinarController::class, 'index'])->name('admin.webinars.index');
    Route::get('/admin/webinars/create', [WebinarController::class, 'create'])->name('admin.webinars.create');
    Route::post('/admin/webinars', [WebinarController::class, 'store'])->name('admin.webinars.store');
    Route::get('/admin/webinars/{webinar}/edit', [WebinarController::class, 'edit'])->name('admin.webinars.edit');
    Route::get('/admin/webinars/{webinar}/live-control', [WebinarController::class, 'live'])->name('admin.webinars.live');
    Route::put('/admin/webinars/{webinar}/live-control', [WebinarController::class, 'controls'])->name('admin.webinars.controls');
    Route::put('/admin/webinars/{webinar}/announcement', [WebinarController::class, 'announcement'])->name('admin.webinars.announcement');
    Route::get('/admin/webinars/{webinar}', [WebinarController::class, 'show'])->name('admin.webinars.show');
    Route::put('/admin/webinars/{webinar}', [WebinarController::class, 'update'])->name('admin.webinars.update');
    Route::patch('/admin/webinars/{webinar}/status', [WebinarController::class, 'status'])->name('admin.webinars.status');
    Route::delete('/admin/webinars/{webinar}', [WebinarController::class, 'destroy'])->name('admin.webinars.destroy');
    Route::post('/admin/webinars/{webinar}/clone', [WebinarController::class, 'clone'])->name('admin.webinars.clone');
    Route::get('/admin/polls', [PollController::class, 'index'])->name('admin.polls.index');
    Route::get('/admin/polls/create', [PollController::class, 'create'])->name('admin.polls.create');
    Route::post('/admin/polls', [PollController::class, 'store'])->name('admin.polls.store');
    Route::get('/admin/polls/{poll}/edit', [PollController::class, 'edit'])->name('admin.polls.edit');
    Route::get('/admin/polls/{poll}', [PollController::class, 'show'])->name('admin.polls.show');
    Route::put('/admin/polls/{poll}', [PollController::class, 'update'])->name('admin.polls.update');
    Route::patch('/admin/polls/{poll}/status', [PollController::class, 'status'])->name('admin.polls.status');
    Route::delete('/admin/polls/{poll}', [PollController::class, 'destroy'])->name('admin.polls.destroy');
    Route::post('/admin/polls/{poll}/duplicate', [PollController::class, 'duplicate'])->name('admin.polls.duplicate');
    Route::get('/admin/certificates', [CertificateController::class, 'index'])->name('admin.certificates.index');
    Route::get('/admin/certificates/create', [CertificateController::class, 'create'])->name('admin.certificates.create');
    Route::get('/admin/certificates/{webinar}/edit', [CertificateController::class, 'edit'])->name('admin.certificates.edit');
    Route::put('/admin/certificates/{webinar}', [CertificateController::class, 'update'])->name('admin.certificates.update');
    Route::patch('/admin/certificates/{webinar}/visibility', [CertificateController::class, 'visibility'])->name('admin.certificates.visibility');
    Route::get('/admin/certificate-queue', [CertificateController::class, 'queue'])->name('admin.certificates.queue');
    Route::patch('/admin/certificate-queue/{certificate}', [CertificateController::class, 'decision'])->name('admin.certificates.decision');
    Route::get('/admin/certificates/logs', [CertificateController::class, 'logs'])->name('admin.certificates.logs');
    Route::get('/admin/permissions', [PermissionController::class, 'index'])->name('admin.permissions.index');
    Route::get('/admin/permissions/create', [PermissionController::class, 'create'])->name('admin.permissions.create');
    Route::get('/admin/permissions/{user}/{webinar}/edit', [PermissionController::class, 'edit'])->name('admin.permissions.edit');
    Route::put('/admin/permissions', [PermissionController::class, 'update'])->name('admin.permissions.update');
    Route::delete('/admin/permissions/{user}/{webinar}', [PermissionController::class, 'destroy'])->name('admin.permissions.destroy');
    Route::get('/admin/speakers', [SpeakerController::class, 'index'])->name('admin.speakers.index');
    Route::get('/admin/speakers/create', [SpeakerController::class, 'create'])->name('admin.speakers.create');
    Route::post('/admin/speakers', [SpeakerController::class, 'store'])->name('admin.speakers.store');
    Route::get('/admin/speakers/{speaker}/edit', [SpeakerController::class, 'edit'])->name('admin.speakers.edit');
    Route::put('/admin/speakers/{speaker}', [SpeakerController::class, 'update'])->name('admin.speakers.update');
    Route::delete('/admin/speakers/{speaker}', [SpeakerController::class, 'destroy'])->name('admin.speakers.destroy');
    Route::delete('/admin/speakers', [SpeakerController::class, 'bulkDelete'])->name('admin.speakers.bulk-destroy');
    Route::patch('/admin/speakers/{speaker}/status', [SpeakerController::class, 'toggle'])->name('admin.speakers.toggle');
    Route::get('/admin/general-settings/site', [GeneralSettingsController::class, 'site'])->name('admin.general.site');
    Route::put('/admin/general-settings/site', [GeneralSettingsController::class, 'updateSite'])->name('admin.general.site.update');
    Route::get('/admin/general-settings/banners', [GeneralSettingsController::class, 'banners'])->name('admin.general.banners');
    Route::get('/admin/general-settings/banners/create', fn (GeneralSettingsController $controller) => $controller->bannerForm())->name('admin.general.banners.create');
    Route::post('/admin/general-settings/banners', [GeneralSettingsController::class, 'saveBanner'])->name('admin.general.banners.store');
    Route::get('/admin/general-settings/banners/{banner}/edit', fn (Banner $banner, GeneralSettingsController $controller) => $controller->bannerForm($banner))->name('admin.general.banners.edit');
    Route::put('/admin/general-settings/banners/{banner}', fn (Request $request, Banner $banner, GeneralSettingsController $controller) => $controller->saveBanner($request, $banner))->name('admin.general.banners.update');
    Route::delete('/admin/general-settings/banners/{banner}', [GeneralSettingsController::class, 'destroyBanner'])->name('admin.general.banners.destroy');
    Route::delete('/admin/general-settings/banners', [GeneralSettingsController::class, 'bulkDeleteBanners'])->name('admin.general.banners.bulk-destroy');
    Route::patch('/admin/general-settings/banners/{banner}/status', [GeneralSettingsController::class, 'toggleBanner'])->name('admin.general.banners.toggle');
    Route::put('/admin/general-settings/banners-order', [GeneralSettingsController::class, 'reorderBanners'])->name('admin.general.banners.reorder');
    Route::get('/admin/general-settings/brands', [GeneralSettingsController::class, 'brands'])->name('admin.general.brands');
    Route::get('/admin/general-settings/brands/create', fn (GeneralSettingsController $controller) => $controller->brandForm())->name('admin.general.brands.create');
    Route::post('/admin/general-settings/brands', [GeneralSettingsController::class, 'saveBrand'])->name('admin.general.brands.store');
    Route::get('/admin/general-settings/brands/{brand}/edit', fn (Brand $brand, GeneralSettingsController $controller) => $controller->brandForm($brand))->name('admin.general.brands.edit');
    Route::put('/admin/general-settings/brands/{brand}', fn (Request $request, Brand $brand, GeneralSettingsController $controller) => $controller->saveBrand($request, $brand))->name('admin.general.brands.update');
    Route::delete('/admin/general-settings/brands/{brand}', [GeneralSettingsController::class, 'destroyBrand'])->name('admin.general.brands.destroy');
    Route::delete('/admin/general-settings/brands', [GeneralSettingsController::class, 'bulkDeleteBrands'])->name('admin.general.brands.bulk-destroy');
    Route::patch('/admin/general-settings/brands/{brand}/status', [GeneralSettingsController::class, 'toggleBrand'])->name('admin.general.brands.toggle');
    Route::view('/admin/users/1', 'pages.admin.resource', ['title' => 'User Details', 'type' => 'detail']);
    Route::get('/admin/sub-admins', [SubAdminController::class, 'index'])->name('admin.subadmins.index');
    Route::get('/admin/sub-admins/create', [SubAdminController::class, 'create'])->name('admin.subadmins.create');
    Route::post('/admin/sub-admins', [SubAdminController::class, 'store'])->name('admin.subadmins.store');
    Route::get('/admin/sub-admins/{subAdmin}/edit', [SubAdminController::class, 'edit'])->name('admin.subadmins.edit');
    Route::put('/admin/sub-admins/{subAdmin}', [SubAdminController::class, 'update'])->name('admin.subadmins.update');
    Route::delete('/admin/sub-admins/{subAdmin}', [SubAdminController::class, 'destroy'])->name('admin.subadmins.destroy');
    Route::get('/admin/reports', [ReportController::class, 'index'])->name('admin.reports.index');
    Route::get('/admin/chats', [ChatController::class, 'index'])->name('admin.chats.index');
    Route::get('/admin/chats/{webinar}', [ChatController::class, 'show'])->name('admin.chats.show');
    Route::post('/admin/chats/{webinar}', [ChatController::class, 'store'])->name('admin.chats.store');
    Route::delete('/admin/chats/{webinar}/messages/{message}', [ChatController::class, 'destroy'])->name('admin.chats.messages.destroy');
    Route::get('/admin/comments', [EngagementController::class, 'comments'])->name('admin.comments.index');
    Route::get('/admin/comments/{webinar}', [EngagementController::class, 'commentsShow'])->name('admin.comments.show');
    Route::delete('/admin/comments/{webinar}/{item}', [EngagementController::class, 'removeComment'])->name('admin.comments.destroy');
    Route::get('/admin/feedback', [EngagementController::class, 'feedback'])->name('admin.feedback.index');
    Route::get('/admin/feedback/{webinar}', [EngagementController::class, 'feedbackShow'])->name('admin.feedback.show');
    Route::patch('/admin/feedback/{webinar}/{item}', [EngagementController::class, 'updateFeedback'])->name('admin.feedback.update');
    Route::get('/admin/questions', [QuestionController::class, 'index'])->name('admin.questions.index');
    Route::patch('/admin/questions/{question}', [QuestionController::class, 'update'])->name('admin.questions.update');
    Route::post('/admin/questions/{question}/answer', [QuestionController::class, 'answer'])->name('admin.questions.answer');
    Route::get('/admin/notifications', [NotificationController::class, 'index'])->name('admin.notifications.index');
    Route::get('/admin/notifications/create', [NotificationController::class, 'create'])->name('admin.notifications.create');
    Route::post('/admin/notifications', [NotificationController::class, 'store'])->name('admin.notifications.store');
    Route::view('/admin/cms', 'pages.admin.resource', ['title' => 'CMS Dashboard', 'type' => 'cms']);
    Route::view('/admin/cms/homepage', 'pages.admin.resource', ['title' => 'Homepage CMS', 'type' => 'cms-form']);
    Route::redirect('/admin/settings', '/admin/profile');
});

Route::redirect('/sub-admin/login', '/admin/login');
Route::redirect('/sub-admin/dashboard', '/admin/dashboard');
