@extends('layouts.portal')
@section('title','Live Control · '.$webinar->title)
@section('content')
<div class="page-heading pt-2"><div><span class="eyebrow">LIVE CONTROL</span><h1>{{ $webinar->title }}</h1><p>These controls belong only to this webinar.</p></div><div class="d-flex align-items-center gap-2"><a class="btn btn-outline-secondary" href="{{ route('admin.webinars.index') }}"><i class="bi bi-arrow-left me-1"></i>Webinars list</a><a class="btn btn-light" href="{{ route('admin.webinars.show',$webinar) }}"><i class="bi bi-eye me-1"></i>Overview</a></div></div>
@if(session('status'))<div class="alert alert-success">{{ session('status') }}</div>@endif
<div class="control-grid" data-live-viewers data-webinar-id="{{ $webinar->id }}"><div class="control-stage"><div class="control-preview"><span class="status-badge {{ $webinar->status }}">{{ strtoupper($webinar->status) }}</span><i class="bi bi-{{ $webinar->icon ?: 'camera-video' }} display-1"></i><h2>{{ $webinar->title }}</h2><p>{{ $webinar->short_description }}</p></div></div><div><div class="stats-grid control-stats"><x-stat-card label="Live viewers" :value="$liveViewers" icon="eye" :live="true" data-live-viewer-count /><x-stat-card label="Registered" :value="$webinar->registrations_count" icon="people" /><x-stat-card label="Capacity" :value="$webinar->max_attendees ?: 'Unlimited'" icon="person-check" tone="blue" /></div><form class="panel-card mt-3" method="POST" action="{{ route('admin.webinars.controls',$webinar) }}" data-admin-live-controls>@csrf @method('PUT')<div class="panel-title"><h3>Webinar controls</h3></div><div class="switch-list"><label style="display:flex;align-items:center;justify-content:space-between;gap:16px"><span style="white-space:nowrap;font-weight:600">Status</span><select class="form-select" name="status" style="width:auto;min-width:160px;font-weight:650;padding:6px 36px 6px 14px;border-radius:10px">@foreach(['scheduled','live','completed','cancelled'] as $status)<option value="{{ $status }}" @selected($webinar->status===$status)>{{ ucfirst($status) }}</option>@endforeach</select></label><label style="display:flex;align-items:center;justify-content:space-between"><span style="white-space:nowrap">Live chat</span><input type="checkbox" name="chat_enabled" value="1" @checked($webinar->chat_enabled)></label><label style="display:flex;align-items:center;justify-content:space-between"><span style="white-space:nowrap">Comments</span><input type="checkbox" name="comments_enabled" value="1" @checked($webinar->comments_enabled)></label><label style="display:flex;align-items:center;justify-content:space-between"><span style="white-space:nowrap">Polls</span><input type="checkbox" name="polls_enabled" value="1" @checked($webinar->polls_enabled)></label><label style="display:flex;align-items:center;justify-content:space-between"><span style="white-space:nowrap">Feedback</span><input type="checkbox" name="feedback_enabled" value="1" @checked($webinar->feedback_enabled)></label></div><div class="d-flex align-items-center gap-2 mt-3"><button class="btn btn-gradient">Save & return to listing</button><a href="{{ route('admin.webinars.index') }}" class="btn btn-light">Back</a></div></form>
@php($pinned = data_get($webinar->settings, 'pinned_announcement', []))
<form class="panel-card mt-3" method="POST" action="{{ route('admin.webinars.announcement', $webinar) }}" data-admin-announcement-form>@csrf @method('PUT')<div class="panel-title"><h3>Important Note / Announcement Banner (Landing Page & Live Room)</h3></div><div class="mb-3"><label class="form-label small text-muted">Announcement message</label><textarea class="form-control form-control-sm" name="message" rows="2" placeholder="e.g. Special offer: Use coupon LIVE50 to get 50% off!">{{ $pinned['message'] ?? '' }}</textarea></div><div class="row g-2 mb-3"><div class="col-6"><label class="form-label small text-muted">Button label (optional)</label><input type="text" class="form-control form-control-sm" name="button_text" value="{{ $pinned['button_text'] ?? '' }}" placeholder="e.g. Claim Offer"></div><div class="col-6"><label class="form-label small text-muted">Button URL (optional)</label><input type="url" class="form-control form-control-sm" name="button_url" value="{{ $pinned['button_url'] ?? '' }}" placeholder="https://example.com/offer"></div></div><div class="form-check form-switch mb-3"><input class="form-check-input" type="checkbox" name="enabled" value="1" id="pinBannerSwitch" @checked(!empty($pinned['enabled']))><label class="form-check-label small" for="pinBannerSwitch">Show important note banner on landing page & live room</label></div><button class="btn btn-gradient btn-sm">Update pinned banner</button></form></div></div>
@endsection
