@extends('layouts.app')
@section('shell')
<header class="public-header sticky-top"><nav class="navbar navbar-expand-lg"><div class="container py-2"><x-site-brand /><button class="navbar-toggler border-0" data-bs-toggle="collapse" data-bs-target="#publicNav"><span class="navbar-toggler-icon"></span></button><div class="collapse navbar-collapse" id="publicNav"><ul class="navbar-nav mx-auto gap-lg-3"><li><a class="nav-link" href="/">Home</a></li><li><a class="nav-link" href="/webinars">Webinars</a></li><li><a class="nav-link" href="/#speakers">Speakers</a></li><li><a class="nav-link" href="/#categories">Categories</a></li><li><a class="nav-link" href="/#about">About</a></li></ul><div class="d-flex gap-2">@guest<button type="button" class="btn btn-ghost" data-bs-toggle="modal" data-bs-target="#micrositeLoginModal">Log in</button><button type="button" class="btn btn-gradient" data-bs-toggle="modal" data-bs-target="#micrositeRegisterModal">Get started</button>@else<a class="btn btn-gradient" href="{{ route('dashboard') }}">Dashboard</a>@endguest</div></div></div></nav></header>
@php($authNotice=session('auth_status') ?: session('registration_status'))
@if($authNotice)<div class="auth-redirect-notice" role="status" aria-live="polite"><span class="auth-redirect-icon"><i class="bi bi-check2"></i></span><div><strong>{{ $authNotice }}</strong>@if(session('auth_redirect'))<small>Redirecting in <b data-auth-countdown>3</b> seconds…</small>@endif</div></div>@endif
<main>@yield('content')</main>@hasSection('footer') @yield('footer') @endif
@guest
@hasSection('auth-modals') @yield('auth-modals') @else @include('components.frontend-auth', ['authWebinar'=>null]) @endif
@endguest
@if($authNotice)<style>.auth-redirect-notice{position:fixed;z-index:4000;top:90px;right:24px;max-width:min(430px,calc(100vw - 32px));display:flex;align-items:center;gap:13px;padding:16px 18px;border:1px solid #d1fae5;border-radius:16px;background:#fff;color:#172033;box-shadow:0 22px 60px #1720332b}.auth-redirect-icon{width:40px;height:40px;display:grid;place-items:center;flex:none;border-radius:12px;background:#dcfce7;color:#15803d;font-size:1.25rem}.auth-redirect-notice div{display:grid;gap:3px}.auth-redirect-notice strong{font-size:.9rem}.auth-redirect-notice small{color:#64748b}@media(max-width:600px){.auth-redirect-notice{top:74px;right:16px;left:16px}}</style>@endif
@if(session('auth_redirect'))<script>document.addEventListener('DOMContentLoaded',()=>{let seconds=3;const counter=document.querySelector('[data-auth-countdown]');const timer=setInterval(()=>{seconds-=1;if(counter)counter.textContent=Math.max(seconds,0);if(seconds<=0){clearInterval(timer);window.location.assign(@json(session('auth_redirect')))}},1000)})</script>@endif
@endsection
